import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/navbar";
import { NextIntlClientProvider, useLocale, useMessages } from "next-intl";
import "bootstrap/dist/css/bootstrap.css";


const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "USERS PORTAL",
  description: "Generated by create next app",
};

interface RootLayoutProps{
  children: React.ReactNode;
  params:{
    locale:string;
  };
}

export default function RootLayout({
  children,
  params:{ locale },
}: Readonly<RootLayoutProps>) {
  const messages = useMessages();
  // const locale = useLocale();
  // if(params.locale !== locale){
  //   notFound()
  // }

    return (
    <html lang={locale}>
      <body className={inter.className}>
      <NextIntlClientProvider locale={locale} messages={messages}>
        <Navbar/>
        <div className="background-container">{children}</div>
        </NextIntlClientProvider>
      </body>
    </html>);
  }

  
// export default function RootLayout({
//     children,
//   }: Readonly<{
//     children: React.ReactNode;
//   }>) {
//     return children;
//   }